remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Author info (optional but good for SEO)
author:
  name: "Guru Dayal"
  email: "gurudayal132@gmail.com"

# Include custom CSS
include:
  - assets/css/style.css

# Markdown & formatting
markdown: kramdown
highlighter: rouge

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
