remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site identity
title: "Guru Dayal"
description: "A blue-team focused portfolio highlighting my work in detection engineering, threat hunting, and security operations."

# Author info (optional but good for SEO)
author:
  name: "Guru Dayal"
  email: "gurudayal132@gmail.com"

# URL settings
# (Leave url/baseurl blank for user GitHub Pages: username.github.io)
url: "https://gurudayal.github.io"
baseurl: ""

# Include custom CSS
include:
  - assets/css/style.css

# Markdown & formatting
markdown: kramdown
highlighter: rouge

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
